### ISSUE TITLE
Add Icon

### ISSUE THREAD

**Issue by Alpha-thebaby** [theendercore/NPCTraderMod#2]
![Butcher](https://user-images.githubusercontent.com/115327854/211607006-5eee19c3-5093-45bc-bd87-8ab15b5d649b.png)
![qwdqqwddqdqw](https://user-images.githubusercontent.com/115327854/211607010-e0efa0e1-81b1-4cdf-87f9-dfae82cf2acf.jpg)

**Comment by theendercore** [comment]
not a priority

**Comment by theendercore** [comment]
also dot attach data like this to issues
